services:

  mysql:
    image: mysql:8.4
    restart: unless-stopped

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    environment:
      MYSQL_ROOT_PASSWORD: senha!@
      MYSQL_DATABASE: agendamento_espacos
      MYSQL_USER: app_user
      MYSQL_PASSWORD: senha!@

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - dokploy-network

    expose:
      - "3306"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:

      NODE_ENV: production

      PORT: "3000"

      DB_HOST: mysql
      DB_PORT: "3306"

      DB_USER: app_user
      DB_PASS: senha!@

      DB_NAME: agendamento_espacos

      DB_LOGGING: false

      JWT_SECRET: 9f3c2a7b8d6e4f1c9a0d8b7e6f5c4a3d2b1e0f9c8a7b6d5c4

      FRONTEND_URL: https://agendamentos1.lab7.cloud


    networks:
      - dokploy-network


    depends_on:
      mysql:
        condition: service_healthy


    expose:
      - "3000"



  frontend:

    build:
      context: ./frontend
      dockerfile: Dockerfile

      args:

        VITE_API_URL: https://api-agendamentos1.lab7.cloud/api


    restart: unless-stopped


    networks:
      - dokploy-network


    depends_on:
      backend:
        condition: service_healthy


    expose:
      - "80"



volumes:

  mysql_data:


networks:

  dokploy-network:

    external: true